#!/bin/bash

NAME="alf_db"                                             # Name of the application 
DJANGODIR=/home/mint/alf_db                               # Django project directory (CAMBIAR MINT POR NOMBRE DE USUARIO)
SOCKFILE=/tmp/alf_db.sock                                 # we will communicte using this unix socket 
USER=mint                                                 # the user to run as (CAMBIAR MINT POR NOMBRE DE USUARIO)
GROUP=mint                                                # the group to run as (CAMBIAR MINT POR NOMBRE DE USUARIO)
NUM_WORKERS=3                                             # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=alf.settings                       # which settings file should Django use
DJANGO_WSGI_MODULE=alf.wsgi                               # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ./alf_env/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ./alf_env/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
 --name $NAME \
 --workers $NUM_WORKERS \
 --user=$USER --group=$GROUP \
 --bind=unix:$SOCKFILE \
 --log-level=debug \
 --log-file=-