# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alf_db', '0002_auto_20170607_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
    ]
