# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alf_db', '0002_auto_20170808_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_reception',
            field=models.BooleanField(default=False),
        ),
    ]
