# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alf_db', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
    ]
