# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alf_db', '0006_auto_20170619_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivery_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
