# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alf_db', '0007_transaction_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='check_reception',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
