# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alf_db', '0008_transaction_check_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='check_reception',
            field=models.NullBooleanField(default=None, max_length=20),
        ),
    ]
