# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alf_db', '0009_auto_20170626_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='check_reception',
            field=models.BooleanField(default=False),
        ),
    ]
