# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alf_db', '0010_auto_20170626_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtspurchased',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alf_db.Product'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alf_db.Customer'),
        ),
    ]
