# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alf_db', '0011_auto_20170626_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtspurchased',
            name='product',
        ),
        migrations.RemoveField(
            model_name='produtspurchased',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='products',
            field=models.ManyToManyField(to='alf_db.Product'),
        ),
        migrations.DeleteModel(
            name='ProdutsPurchased',
        ),
    ]
