# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alf_db', '0013_transaction_transaction_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_images',
            field=models.ImageField(blank=True, null=True, upload_to='transaction_images'),
        ),
    ]
